server:
  port: 8001

spring:
  application:
    name: service

  datasource:
    url: jdbc:mysql://localhost:3306/cxb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver #this is different with yangge
    type: com.alibaba.druid.pool.DruidDataSource